spring:
  application:
    name: zuul
zuul:
  ignoredServices: "*"
  routes:
    registration:
      path: /v1/registration/**
      serviceId: Registration
    coupons:
      path: /v1/coupons/**
      serviceId: Coupons
  prefix: /api

server:
  port: 8080
