eureka:
  instance:
    prefer-ip-address: true

spring:
  application:
    name: Registration

management:
  endpoints:
    web:
      exposure:
        include: refresh, hystrix.stream


resilience4j:
  ratelimiter:
    instances:
      Register:
        limitForPeriod: 10
        limitRefreshPeriod: 1000000
        timeoutDuration: 1000ms
