CREATE TABLE CART (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY NOT NULL
);


CREATE TABLE CART_ITEM (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY NOT NULL,
  quantity NUMBER NOT NULL,
  price NUMBER NOT NULL,
  name VARCHAR(255) NOT NULL,
  CART_ID BIGINT NOT NULL
);
