insert into CUSTOMER(id, FIRST_NAME, LAST_NAME) values (1, 'Piotr', 'Nowak');
insert into CUSTOMER(id, FIRST_NAME, LAST_NAME) values (2, 'Jan', 'Kowalski');
insert into CUSTOMER(id, FIRST_NAME, LAST_NAME) values (3, 'Grzegorz', 'Kwiatkowski');
insert into CUSTOMER(id, FIRST_NAME, LAST_NAME) values (4, 'Piotr', 'Nowak');
insert into CUSTOMER(id, FIRST_NAME, LAST_NAME) values (5, 'Piotr', 'Zielony');
insert into CUSTOMER(id, FIRST_NAME, LAST_NAME) values (6, 'Grzegorz', 'Rejent');
insert into CUSTOMER(id, FIRST_NAME, LAST_NAME) values (7, 'Jan', 'Nowak');
insert into CUSTOMER(id, FIRST_NAME, LAST_NAME) values (8, 'Piotr', 'Kwiatkowski');
insert into CUSTOMER(id, FIRST_NAME, LAST_NAME) values (9, 'Grzegorz', 'Kowalski');
insert into CUSTOMER(id, FIRST_NAME, LAST_NAME) values (10, 'Sebastian', 'Zielony');


insert into ADDRESS(id, CITY, STREET, CUSTOMER_ID) values (1, 'a', 'a', 1);
insert into ADDRESS(id, CITY, STREET, CUSTOMER_ID) values (2, 'a', 'a', 1);
insert into ADDRESS(id, CITY, STREET, CUSTOMER_ID) values (3, 'a', 'a', 2);
insert into ADDRESS(id, CITY, STREET, CUSTOMER_ID) values (4, 'a', 'a', 2);
insert into ADDRESS(id, CITY, STREET, CUSTOMER_ID) values (5, 'a', 'a', 3);
insert into ADDRESS(id, CITY, STREET, CUSTOMER_ID) values (6, 'a', 'a', 3);
insert into ADDRESS(id, CITY, STREET, CUSTOMER_ID) values (7, 'a', 'a', 4);
insert into ADDRESS(id, CITY, STREET, CUSTOMER_ID) values (8, 'a', 'a', 4);
insert into ADDRESS(id, CITY, STREET, CUSTOMER_ID) values (9, 'a', 'a', 5);
insert into ADDRESS(id, CITY, STREET, CUSTOMER_ID) values (10, 'a', 'a', 5);
insert into ADDRESS(id, CITY, STREET, CUSTOMER_ID) values (11, 'a', 'a', 6);
insert into ADDRESS(id, CITY, STREET, CUSTOMER_ID) values (12, 'a', 'a', 6);
insert into ADDRESS(id, CITY, STREET, CUSTOMER_ID) values (13, 'a', 'a', 7);
insert into ADDRESS(id, CITY, STREET, CUSTOMER_ID) values (14, 'a', 'a', 7);
insert into ADDRESS(id, CITY, STREET, CUSTOMER_ID) values (15, 'a', 'a', 8);
insert into ADDRESS(id, CITY, STREET, CUSTOMER_ID) values (16, 'a', 'a', 8);
insert into ADDRESS(id, CITY, STREET, CUSTOMER_ID) values (17, 'a', 'a', 9);
insert into ADDRESS(id, CITY, STREET, CUSTOMER_ID) values (18, 'a', 'a', 9);
insert into ADDRESS(id, CITY, STREET, CUSTOMER_ID) values (19, 'a', 'a', 10);
insert into ADDRESS(id, CITY, STREET, CUSTOMER_ID) values (20, 'a', 'a', 10);
